services:
  timesketch-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - TIMESKETCH_HOST=${TIMESKETCH_HOST}
      - TIMESKETCH_PORT=${TIMESKETCH_PORT}
      - TIMESKETCH_USER=${TIMESKETCH_USER}
      - TIMESKETCH_PASSWORD=${TIMESKETCH_PASSWORD}
    volumes:
      - ../:/app
    networks:
      - default

networks:
  default:
    driver: bridge
